// loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';
export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';
export const ARTS_ENABLE_LOADER = 'ARTS_ENABLE_LOADER';
export const ARTS_DISABLE_LOADER = 'ARTS_DISABLE_LOADER';

// theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_LOADING_ENDED = 'LOGIN_LOADING_ENDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

//signup
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_LOADING_ENDED = 'SIGNUP_LOADING_ENDED';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

//arts
export const ARTS_REQUEST = 'ARTS_REQUEST';
export const ARTS_LOADING_ENDED = 'ARTS_LOADING_ENDED';

export const ARTS_FAILED = 'ARTS_FAILED';
export const ARTS_RESPONSE = 'ARTS_RESPONSE';


